# used for local testing
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: food-facts-friends-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: food_facts_friends_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
